### ISSUE TITLE
1.13 startup error

### ISSUE THREAD

**Issue by mrcoffee1026** [lenis0012/Marriage#35]
[17:18:00] [Server thread/INFO]: [Marriage] Loading dependencies...
[17:18:00] [Server thread/INFO]: [Marriage] Loading commands...
[17:18:00] [Server thread/INFO]: [Marriage] Loading database...
[17:18:00] [Server thread/INFO]: [Marriage] Loading listeners...
[17:18:00] [Server thread/WARN]: java.lang.NullPointerException
[17:18:00] [Server thread/WARN]: 	at com.lenis0012.bukkit.marriage2.libs.pluginutils.misc.Reflection.getMethod(Reflection.java:82)
[17:18:00] [Server thread/WARN]: 	at com.lenis0012.bukkit.marriage2.libs.pluginutils.misc.Reflection.getNMSMethod(Reflection.java:92)
[17:18:00] [Server thread/WARN]: 	at com.lenis0012.bukkit.marriage2.listeners.KissListener.<init>(KissListener.java:23)
[17:18:00] [Server thread/WARN]: 	at com.lenis0012.bukkit.marriage2.internal.MarriageCore.registerListeners(MarriageCore.java:87)
[17:18:00] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:18:00] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[17:18:00] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[17:18:00] [Server thread/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[17:18:00] [Server thread/WARN]: 	at com.lenis0012.bukkit.marriage2.internal.MarriagePlugin.executeMethods(MarriagePlugin.java:90)
[17:18:00] [Server thread/WARN]: 	at com.lenis0012.bukkit.marriage2.internal.MarriagePlugin.enable(MarriagePlugin.java:64)
[17:18:00] [Server thread/WARN]: 	at com.lenis0012.bukkit.marriage2.libs.pluginutils.PluginHolder.onEnable(PluginHolder.java:27)
[17:18:00] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[17:18:00] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339)
[17:18:00] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[17:18:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:431)
[17:18:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:345)
[17:18:00] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:584)
[17:18:00] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:546)
[17:18:00] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:424)
[17:18:00] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294)
[17:18:00] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:702)
[17:18:00] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Unknown Source)
[17:18:00] [Server thread/INFO]: [Marriage] Hooking with PlotSquared v18.10.13-b6d4872-2048
[17:18:00] [Server thread/INFO]: [Marriage] Loading updater...
[17:18:00] [Server thread/INFO]: [Marriage] Loading converter...
[17:18:00] [Server thread/INFO]: [Marriage] Completed plugin load stage.

[17:22:47] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-f6a273b-cd6252a (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)[m
[17:22:47] [Server thread/INFO]: Checking version, please wait...[m
[17:22:47] [Thread-27/INFO]: You are running the latest version[m
using Marriage-Spigot-2.0.18.jar (jenkins build for 1.13?)
-- | --

or link here: https://pastebin.com/fdcD39Zi

**Comment by lenis0012** [comment]
Try version 2.0.19
