### ISSUE TITLE
Update to 1.13 Spigot

### ISSUE THREAD

**Issue by KissOfFate** [lenis0012/Marriage#37]
I'm not asking for a full conversion/full massive update with new features, however I would like to see a compatibility update sometime soon :) I do not like other 1.13 marriage plugins and I enjoy this one, so if you could make a simple compatibility update, it would be much appreciated!

EDIT: #35 is an issue

Also when trying to kiss your partner by shift right clicking them results in an error:
`
[03/19/2019 05:13:13 pm] [ERROR]: Could not pass event PlayerInteractEntityEvent to Marriage v2.0.18
[03/19/2019 05:13:13 pm]: org.bukkit.event.EventException: null
......
[03/19/2019 05:13:13 pm]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
[03/19/2019 05:13:13 pm]: at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
......
[03/19/2019 05:13:13 pm]: Caused by: java.lang.IllegalArgumentException: Can not set float field net.minecraft.server.v1_13_R2.PacketPlayOutWorldParticles.a to null value
`

I pulled out the relevant information regarding this. Thank you <3

**Comment by lenis0012** [comment]
Try version 2.0.19
