### ISSUE TITLE
1.13 PlotSquared error on startup

### ISSUE THREAD

**Issue by mrcoffee1026** [lenis0012/Marriage#38]
Tried new version (2.0.19) as suggested, still get startup error:

```
[10:38:18] [Server thread/ERROR]: [Marriage] Failed to load listeners
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at com.lenis0012.bukkit.marriage2.internal.MarriagePlugin.executeMethods(MarriagePlugin.java:90) ~[?:?]
	at com.lenis0012.bukkit.marriage2.internal.MarriagePlugin.enable(MarriagePlugin.java:64) ~[?:?]
	at com.lenis0012.bukkit.marriage2.libs.pluginutils.PluginHolder.onEnable(PluginHolder.java:27) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.13.2.jar:git-Paper-624]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334) ~[patched_1.13.2.jar:git-Paper-624]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) ~[patched_1.13.2.jar:git-Paper-624]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443) ~[patched_1.13.2.jar:git-Paper-624]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787) ~[patched_1.13.2.jar:git-Paper-624]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NoClassDefFoundError: com/intellectualcrafters/plot/PS
	at com.lenis0012.bukkit.marriage2.listeners.PlotSquaredListener.<init>(PlotSquaredListener.java:18) ~[?:?]
	at com.lenis0012.bukkit.marriage2.internal.MarriageCore.registerListeners(MarriageCore.java:92) ~[?:?]
	... 18 more
Caused by: java.lang.ClassNotFoundException: com.intellectualcrafters.plot.PS
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_191]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:140) ~[patched_1.13.2.jar:git-Paper-624]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[patched_1.13.2.jar:git-Paper-624]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_191]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_191]
	at com.lenis0012.bukkit.marriage2.listeners.PlotSquaredListener.<init>(PlotSquaredListener.java:18) ~[?:?]
	at com.lenis0012.bukkit.marriage2.internal.MarriageCore.registerListeners(MarriageCore.java:92) ~[?:?]
	... 18 more
```

**Comment by lenis0012** [comment]
This issue is related to PlotSquared integration.
Marriage probably is not compatible with the new version.

Thanks for the heads-up

**Comment by mrcoffee1026** [comment]
Yeah that log was from an older version but I got the same error from their later build as found here:
https://ci.athion.net/job/PlotSquared-Breaking/
Whatever the issue was it showed up many ... MANY builds ago, however.  Thanks again!

**Comment by lenis0012** [comment]
@mrcoffee1026  
Should be fixed in the new dev build
https://ci.codemc.io/job/lenis0012/job/Marriage/
