### ISSUE TITLE
Failed to count marriages

### ISSUE THREAD

**Issue by Aira-Sakuranomiya** [lenis0012/Marriage#58]
Server: Paper 1.19.3
System: CentOS

```
[02:14:14 WARN]: [Marriage] Failed to count marriages
java.sql.SQLException: Before start of result set
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[mysql-connector-java-8.0.29.jar:8.0.29]
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.29.jar:8.0.29]
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.29.jar:8.0.29]
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.29.jar:8.0.29]
        at com.mysql.cj.jdbc.result.ResultSetImpl.checkRowPos(ResultSetImpl.java:532) ~[mysql-connector-java-8.0.29.jar:8.0.29]
        at com.mysql.cj.jdbc.result.ResultSetImpl.getObject(ResultSetImpl.java:1322) ~[mysql-connector-java-8.0.29.jar:8.0.29]
        at com.mysql.cj.jdbc.result.ResultSetImpl.getInt(ResultSetImpl.java:830) ~[mysql-connector-java-8.0.29.jar:8.0.29]
        at com.lenis0012.bukkit.marriage2.internal.data.DataManager.countMarriages(DataManager.java:393) ~[Marriage.jar:?]
        at com.lenis0012.bukkit.marriage2.internal.MarriageCore.lambda$loadMetrics$0(MarriageCore.java:74) ~[Marriage.jar:?]
        at com.lenis0012.bukkit.marriage2.libs.bstats.charts.SingleLineChart.getChartData(SingleLineChart.java:24) ~[Marriage.jar:?]
        at com.lenis0012.bukkit.marriage2.libs.bstats.charts.CustomChart.getRequestJsonObject(CustomChart.java:22) ~[Marriage.jar:?]
        at com.lenis0012.bukkit.marriage2.libs.bstats.MetricsBase.lambda$submitData$2(MetricsBase.java:146) ~[Marriage.jar:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
        at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
        at com.lenis0012.bukkit.marriage2.libs.bstats.MetricsBase.submitData(MetricsBase.java:148) ~[Marriage.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.3.jar:git-Paper-384]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.3.jar:git-Paper-384]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1473) ~[paper-1.19.3.jar:git-Paper-384]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:440) ~[paper-1.19.3.jar:git-Paper-384]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.3.jar:git-Paper-384]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-384]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-384]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by lenis0012** [comment]
Thanks. I will look in to this and fix it for the next release.

**Comment by lenis0012** [comment]
@Aira-Sakuranomiya please try the latest dev build.

**Comment by Aira-Sakuranomiya** [comment]
Latest dev build works fine :heart:
